name: ninecoin
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  badges: ^2.0.3
  uuid: ^3.0.6
  android_id: ^0.1.3
  
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.2.5
  flutter_spinkit: ^5.1.0
  http: ^0.13.5
  firebase_messaging: ^14.0.3
  flutter_local_notifications: ^12.0.3
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  image_picker: ^0.8.5+3
  path: ^1.8.0
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  toast: ^0.3.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/
    - assets/pics/
    - assets/prize_gif/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

    - family: Poppins Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

    - family: Poppins SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

    - family: Vollkorn SemiBold
      fonts:
        - asset: assets/fonts/Vollkorn-SemiBold.ttf
          weight: 600
